/**
 * Extension token issuance ("claim").
 *
 * The web app, once logged in, exchanges its session for an opaque API
 * token that the extension will present on every signed request. Each call
 * binds one P-256 public key — the one generated by that specific browser
 * install — so a token only ever signs requests verifiable against the
 * install it was issued for. The raw token is shown exactly once; from that
 * moment only its SHA-256 hash exists on the server.
 *
 * One claim per install: repeat claims simply mint further
 * (token, key) pairs, each independently revocable, which is what the
 * account page's "sign out" does later (Phase 4).
 */
import { importP256Jwk, randomToken, sha256Hex, type P256Jwk } from '@squiggle/shared';

import type { Clock } from '../lib/clock';
import { apiError, type Outcome } from '../lib/errors';
import type { Db, UserRow } from '../db/types';

/** Extension tokens last 90 days; after that the install must re-auth. */
export const EXTENSION_TOKEN_TTL_MS = 90 * 24 * 60 * 60 * 1000;

export interface ClaimDeps {
  db: Db;
  clock: Clock;
}

export async function claimExtensionToken(
  deps: ClaimDeps,
  user: UserRow,
  publicKeyJwk: unknown,
): Promise<Outcome<{ token: string; keyId: string; userId: string }>> {
  const jwk = normalizeP256Jwk(publicKeyJwk);
  if (!jwk) {
    return apiError('invalid_key', 'Expected a P-256 (EC) public key in JWK form.');
  }
  try {
    // Importing proves the coordinates are a usable key, not just shape.
    await importP256Jwk(jwk);
  } catch {
    return apiError('invalid_key', 'The public key could not be imported.');
  }

  const now = deps.clock.now();
  const key = await deps.db.createExtensionKey(user.id, JSON.stringify(jwk), now);
  const token = randomToken(32);
  await deps.db.createToken({
    userId: user.id,
    keyId: key.id,
    tokenHash: await sha256Hex(token),
    now,
    ttlMs: EXTENSION_TOKEN_TTL_MS,
  });

  return { ok: true, token, keyId: key.id, userId: user.id };
}

/** Accept only a structurally valid P-256 EC public JWK; strip extra members. */
function normalizeP256Jwk(value: unknown): P256Jwk | null {
  if (typeof value !== 'object' || value === null) return null;
  const o = value as Record<string, unknown>;
  if (o.kty !== 'EC' || o.crv !== 'P-256') return null;
  if (typeof o.x !== 'string' || o.x.length === 0) return null;
  if (typeof o.y !== 'string' || o.y.length === 0) return null;
  return { kty: 'EC', crv: 'P-256', x: o.x, y: o.y };
}
